server:
  port: 8089
spring:
  kafka:
    bootstrap-servers: localhost:9092
    # producer config
    producer:
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer